### ISSUE TITLE
Nginx won't start

### ISSUE THREAD

**Issue by curtbruns** [vchrisb/vagrant-coprhd#2]
Nginx.conf has settings for IPV6 but the box isn't configured for IPV6.  (Log below).
Some debug I've done:
- I can edit the nginx.conf and remove the IPV6 server entries, but it gets re-generated on every reload/restart.  
- I tried editing the ovfenv.properties file but that didn't seem to help.  
- I don't know about the systool or how genconfig works so not sure how to best solve this?

Thanks!
Curt

coprhd1:~ # service nginx start
Job for nginx.service failed. See "systemctl status nginx.service" and "journalctl -xn" for details.
coprhd1:~ # journalctl -xn
-- Logs begin at Wed 2015-10-07 18:27:23 CEST, end at Wed 2015-10-07 18:29:30 CEST. --
Oct 07 18:28:49 coprhd1.lab.local nginx.wrapper[5129]: nginx: [emerg] the INET6 sockets are not sup
Oct 07 18:28:59 coprhd1.lab.local nginx.wrapper[5141]: nginx: [emerg] the INET6 sockets are not sup
Oct 07 18:29:04 coprhd1.lab.local sshd[5149]: Accepted publickey for vagrant from 10.0.2.2 port 540
Oct 07 18:29:04 coprhd1.lab.local sshd[5149]: pam_unix(sshd:session): session opened for user vagra
Oct 07 18:29:04 coprhd1.lab.local systemd[5151]: pam_unix(systemd-user:session): session opened for
Oct 07 18:29:08 coprhd1.lab.local su[5193]: (to root) vagrant on pts/0
Oct 07 18:29:08 coprhd1.lab.local su[5193]: pam_unix(su-l:session): session opened for user root by
Oct 07 18:29:09 coprhd1.lab.local nginx.wrapper[5240]: nginx: [emerg] the INET6 sockets are not sup
Oct 07 18:29:19 coprhd1.lab.local nginx.wrapper[5338]: nginx: [emerg] the INET6 sockets are not sup
Oct 07 18:29:30 coprhd1.lab.local nginx.wrapper[5391]: nginx: [emerg] the INET6 sockets are not sup

**Comment by vchrisb** [comment]
IPV6 isn't normally causing any issues, though it might be in the nginx configuration. It happens from time to time that the initial CoprHD configuration fails.
Nginx is configured to use "/opt/storageos/conf/storageos.crt" and the cert is only created after initial CoprHD configuration.
Therefore please validate the cert is created and also validate that the CoprHD services are started (storageos...). 
Please have a look at https://coprhd.atlassian.net/wiki/display/COP/How+to+triage+problems+during+CoprHD+installation

In general it is faster to do a "vagrant destroy" and restart the vagrant deployment.

**Comment by curtbruns** [comment]
Thanks for the response.  I believe the issue is with the CoprHD build procedure creating the IPV6 config section in the nginx.conf file even when the VM/Platform only supports IPV4.  So, nothing related to your Vagrant setup.  Thanks!
