### ISSUE TITLE
CoprHD service cannot start

### ISSUE THREAD

**Issue by cy0713** [vchrisb/vagrant-coprhd#3]
Recently I tried to build and deploy CoprHD on my computer, but unfortunately, after successfully build, system always got stuck when starting CoprHD service, shown as following picture. What's worse, the whole Windows showed no response whatever I do and then I had to choose forced shutdown. When I restarted my computer, I cannot start my CoprHD1 VM.
Above is my problem, and I wonder if CoprHD service has demand for underlying hardware resources, so I want to know your deploying environment in detail. And I eagerly look forward to your suggestions on my problem.
![qq 20151116100815](https://cloud.githubusercontent.com/assets/8422890/11172928/3468b1da-8c4a-11e5-898b-afc51940cc8f.jpg)

**Comment by avinashga23** [comment]
I am also facing the same issue on my 8 GB ram i7 laptop. Did you get a workaround for this?

**Comment by vchrisb** [comment]
You need 7 to 8 GB of free memory to get the services successfully launched. On a Windows host with 8 GB of memory in total, there won't be enough free memory.

**Comment by avinashga23** [comment]
Yup. I upgraded the ram to 16gb. Now it works great.

## Regards

Avinash
