### ISSUE TITLE
Syntax error in the Vagrantfile

### ISSUE THREAD

**Issue by avinashga23** [vchrisb/vagrant-coprhd#4]
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /home/avinash/Development/vagrant/vagrant-coprhd-master/Vagrantfile
Line number: 12
Message: NameError: uninitialized constant True

OS Linux mint 17.2

Workaround True must be true in line number 12

**Comment by cy0713** [comment]
You should replace True with true, try it.

**Comment by avinashga23** [comment]
Thanks Chris.

## Regards

Avinash

**Comment by vchrisb** [comment]
thank you, fixed it
