### ISSUE TITLE
really 8GB?

### ISSUE THREAD

**Issue by heckj** [vchrisb/vagrant-coprhd#5]
Just checking - I saw the Vagrant file entry at https://github.com/vchrisb/vagrant-coprhd/blob/master/Vagrantfile#L43 - does CoprHD really want/need 8GB to operate? Could I safely run it for the purposes of poking at it and such in a small memory footprint?

**Comment by vchrisb** [comment]
Yes, you really need 8GB of free memory. Please also see Issue https://github.com/vchrisb/vagrant-coprhd/issues/3

**Comment by heckj** [comment]
Thanks @vchrisb!
